export default types = {
    GET_ACTIVITY_AND_MEDICAL_DETAILS_STARTED: 'GET_ACTIVITY_AND_MEDICAL_DETAILS_STARTED',
    GET_ACTIVITY_AND_MEDICAL_DETAILS_SUCCESS: 'GET_ACTIVITY_AND_MEDICAL_DETAILS_SUCCESS',
    GET_ACTIVITY_AND_MEDICAL_DETAILS_FAILED: 'GET_ACTIVITY_AND_MEDICAL_DETAILS_FAILED',
    GET_WORKOUT_FREQUENCY_SUCCESS: 'GET_WORKOUT_FREQUENCY_SUCCESS',
    GET_WORKOUT_FREQUENCY_FAILED: 'GET_WORKOUT_FREQUENCY_FAILED',
    GET_GOALS_BY_ID_SUCCESS: 'GET_GOALS_BY_ID_SUCCESS',
    GET_GOALS_BY_ID_FAILED: 'GET_GOALS_BY_ID_FAILED',
    GET_WORKOUT_TYPE_SUCCESS: 'GET_WORKOUT_TYPE_SUCCESS',
    GET_WORKOUT_TYPE_FAILED: 'GET_WORKOUT_TYPE_FAILED',
    GET_WORKOUT_PLANS_SUCCESS: 'GET_WORKOUT_PLANS_SUCCESS',
    GET_WORKOUT_PLANS_FAILED: 'GET_WORKOUT_PLANS_FAILED',
}