export default types = {
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
    RESET_REGISTER: 'RESET_REGISTER',
    REGISTER_REQUESTING: 'REGISTER_REQUESTING',
    SET_GLOBAL_BOARD: 'SET_GLOBAL_BOARD',
    SET_AUTH_RESPONSE: 'SET_AUTH_RESPONSE',
}